name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Make gradlew executable
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease

  release:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build Release APK
      run: |
        chmod +x gradlew
        ./gradlew assembleRelease

    - name: Calculate Version
      id: version
      run: |
        LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        VERSION=${LATEST_TAG#v}
        IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
        NEW_PATCH=$((PATCH + 1))
        echo "NEW_VERSION=v$MAJOR.$MINOR.$NEW_PATCH" >> $GITHUB_ENV
        echo "APK_NAME=vihla-release-unsigned-$MAJOR.$MINOR.$NEW_PATCH.apk" >> $GITHUB_ENV
        echo "RELEASE_TITLE=Release Version $MAJOR.$MINOR.$NEW_PATCH" >> $GITHUB_ENV

    - name: Verify and Rename APK
      run: |
        if [ -f "app/build/outputs/apk/release/app-release-unsigned.apk" ]; then
          mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/${{ env.APK_NAME }}
        else
          echo "APK not found at app/build/outputs/apk/release/app-release-unsigned.apk"
          ls -R app/build/outputs/apk/
          exit 1
        fi

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.NEW_VERSION }}
        name: ${{ env.RELEASE_TITLE }}
        files: |
          app/build/outputs/apk/release/${{ env.APK_NAME }}
